export const ENDPOINTS = {
  DASHBOARD: '/vacancies/dashboard',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  ME: '/auth/me',
  VACANCIES: '/vacancies',
  VACANCY: (id: string) => `/vacancies/${id}`,
  SUBMIT_VACANCY: (id: string) => `/vacancies/${id}/submit`,
  RESCORE_VACANCY: (id: string) => `/vacancies/${id}/rescore`,
  APPROVALS_PENDING: '/approvals/pending',
  APPROVE: (id: string) => `/approvals/${id}/approve`,
  REJECT: (id: string) => `/approvals/${id}/reject`,
  CANDIDATES: (vacancyId: string) => `/vacancies/${vacancyId}/candidates`,
  REJECT_CANDIDATE: (vacancyId: string, suggestionId: string) => `/vacancies/${vacancyId}/candidates/${suggestionId}/reject`,
  CANDIDATES_LIST: '/candidates',
  CANDIDATE_DETAIL: (id: string) => `/candidates/${id}`,
  IMPORT_JSON: '/candidates/import/json',
  IMPORT_CSV: '/candidates/import/csv',
  IMPORT_PDF: '/candidates/import/pdf',
  IMPORT_TEMPLATE: '/candidates/import/template',
  RESOLVE_DUPLICATE: '/candidates/import/pdf/resolve',
} as const;
